libp2p/docs

content/concepts/stream-multiplexing.md
=> add stream muxing concept doc

content/reference/glossary.md
=> fix typo in glossary

content/reference/glossary.md
=> Fix a typo

content/tutorials/getting-started/javascript.md
More information on this migration can be seen at [libp2p/js-libp2p/doc/migrations/v0.27-v.28.md](https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.27-v.28.md)
=> chore: update tutorial to 0.28

content/introduction/what-is-libp2p.md
Overall, this content is very well proofread.  This PR contains a few typo fixes I found while reading through it for Hack Week recently.
Closes #90
=> Typo fixes Feb 2021

content/introduction/what-is-libp2p.md
and soften the disclaiming language.
This raises confidence in the doc for readers. (3 years ago is a long time!).
this PR will close #111
=> content/introduction/what-is-libp2p: Remove out-of-date timestamp

content/tutorials/getting-started/javascript.md
See https://github.com/libp2p/js-libp2p/issues/1049#issuecomment-987080135
=> For js-libp2p node >= v16 is required

content/tutorials/getting-started/go.md
As discussed: https://github.com/libp2p/docs/pull/108#issuecomment-999533135
=> Removes `context`. Adds `libp2p`. Adds `$`.

content/tutorials/getting-started/javascript.md
Include statement that mentions the creation of the file where the code is being added.
=> Include statement that mentions the creation of the file where the code is being added

content/tutorials/getting-started/javascript.md
Correctly import the `multiaddr` function.
=> fix import of multiaddr

content/discuss/_index.md
Adds a link to the IPFS Discord group, as per: https://github.com/protocol/docs/issues/9
=> Adds Discord link to `/content/discuss/_index.md`

content/tutorials/getting-started/javascript.md
- When errors in main are uncaught it may be confusing to a user what is happening and how to interpret the logs.
=> Fix error flow of main program in JS tutorial

content/discuss/_index.md
=> Fixes Discord link.

content/tutorials/getting-started/javascript.md
- Update the example code to comply with the to libp2p@37 migration guide
- Update npm modules
- Add example script for installing multiaddr
=> docs(libp2p@37): Update JS tutorial for libp2p@37

content/concepts/addressing.md
update multiaddr spec link to the official spec
=> Update Concepts/Addressing page,

content/_index.md, content/concepts/protocols.md, content/contributing/_index.md, content/discuss/_index.md, content/introduction/_index.md, content/introduction/what-is-libp2p.md
- knocks off a few pending fixes
- ~outdated links~ EDIT: will open in follow up PR
=> Tweaks and minor fixes

content/tutorials/getting-started/go.md
=> Increase required Go version to 1.19 in tutorial

content/concepts/nat.md, content/concepts/stream-multiplexing.md
=> Update links in Concepts docs

.github/workflows/link-check.yml
- Quick config for broken and dead links
> uses [this link check](https://github.com/lycheeverse/lychee-action)
- resolves #22
Please view CI
=> Add action to check links

content/concepts/protocols.md
Seems like functions are no longer available.
Please view the latest Fleek preview [here](https://bafybeif3wzq3qzdynmhuam7cw7ok5pjxe4hpcvpd4i7y6uusdniwlvuudy.on.fleek.co/concepts/protocols/)
=> Remove match function references

layouts/partials/header.html
Closes https://github.com/libp2p/docs/issues/196
Merge when ready.
=> Updates the jquery version being called.

content/_index.md, static/css/theme.css
- Also a temp state for the landing page, but it should link directly to children sections.
Please view the latest Fleek preview [here](https://bafybeibi3voutue5vpcscvuwos2w3labaujy2ekktxhltrlzlg4ffalaxq.on.fleek.co/).
=> Landing page indexes content sections

content/concepts/appendix/glossary.md, content/concepts/contribute/community.md, content/concepts/contribute/contribute.md, content/concepts/fundamentals/addressing.md, content/concepts/fundamentals/overview.md, content/concepts/fundamentals/peers.md, content/concepts/fundamentals/protocols.md, content/concepts/introduction/_index.md, content/concepts/introduction/overview.md, content/concepts/multiplex/_index.md, content/concepts/multiplex/overview.md, content/concepts/multiplex/quic.md, content/concepts/nat/autonat.md, content/concepts/nat/circuit-relay.md, content/concepts/nat/hole-punching.md, content/concepts/nat/overview.md, content/concepts/pubsub/overview.md, content/concepts/secure-comm/noise.md, content/concepts/secure-comm/overview.md, content/concepts/secure-comm/tls.md, content/concepts/security/dos-mitigation.md, content/concepts/security/security-considerations.md, content/concepts/transports/listen-and-dial.md, content/concepts/transports/overview.md, content/concepts/transports/quic.md, content/concepts/transports/webrtc.md, content/concepts/transports/webtransport.md, content/guides/getting-started/go.md, content/guides/getting-started/javascript.md, content/guides/getting-started/rust.md
=> chore:  update redirects and fix formatting

content/concepts/introduction/overview.md
=> fix: overview.md typo

config/_default/menus/menus.en.toml
One way to drive more traffic to the connectivity site
=> feat: make connectivity site a main menu item

content/concepts/introduction/protocols/ping.md
- Adds content for libp2p ping
- closes #251
Section this document lives under will become populated with corresponding PRs.
Please view the latest Fleek preview [here](https://bafybeibnu7jbrxj5lsm3h4bnbf5vxyshhdgpzswshffc6qw3dvg7c4ss5q.on.fleek.co/concepts/introduction/protocols/ping/).
=> feat: ping

content/concepts/introduction/overview.md
- Changes the approach of the introduction to offer a better overview.
- Presents general themes with mention of core components that link to the respective overview document.
TO DO
- Include an architecture/framework diagram to showcase "all of libp2p". (Will be requested to Crcle and doesn't need to hold up pushing these changes).
Please view the latest Fleek preview [here](https://bafybeicpplliiqspagexenwz3bajbfb6ittv5gomwq37jya4vaeq7e26tm.on.fleek.co/concepts/introduction/overview/).
=> update: better intro

content/guides/getting-started/go.md
=> Update go tutorial link

content/concepts/introduction/overview.md
=> fix: internal links in the intro doc

content/concepts/pubsub/gossipsub.md
- Incorporates the content found in the current Publish/Subscribe explainer and adds new content for gossipsub v1.1
- Incorporates the diagrams found in the current Publish/Subscribe explainer
- Addresses #169
=> feat: gossipsub

content/concepts/introduction/overview.md
=> chore: fix typo in overview page

content/concepts/nat/autonat.md
Addresses additional feedback in https://github.com/libp2p/docs/pull/278
Please view the latest Fleek preview [here](https://bafybeiazsxvhg5vzdattrr7tvdymzqhb4s2g6msy6dsfw53amk36fnhcba.on.fleek.co/).
=> update: tweaks to autonat

content/concepts/fundamentals/protocols.md, content/concepts/security/dos-mitigation.md, content/guides/getting-started/go.md
Per deprecation of dedicated module
=> go-libp2p-core -> go-libp2p/core

content/guides/getting-started/javascript.md
=> docs: update ping documentation to use pingService

content/concepts/nat/autonat.md
remove unnecessary colon in `autonat.md`
=> typo: remove unnecessary colon

content/guides/getting-started/javascript.md
The `connectionEncryption` config key was replaced with `connectionEncrypters`
=> docs: update js example for 2.x.x compatibility
