.circleci/config.yml
This is lifted more or less directly from https://github.com/ipfs-shipyard/ipfs-webui/pull/965 and will likely need tweaking before it works here.
=> add initial circleci config

content/_index.md
Using a symlink from the index page to the intro page results in weird breadcrumbs and is probably a bad idea anyway.
This just copies the intro page content to the index page. In the future I think they should be distinct, but this gets something up there quickly.
=> fix breadcrumbs

layouts/partials/custom-header.html, static/css/theme-libp2p.css
I pulled in @raulk's changes from his comment on #26 : 
- body text colour: rgba(20, 21, 45, 0.85)
- headings: #14152D
- line-height: 1.75rem.
- body width: 800px.
- all fonts: "IBM Flex Sans", available on Google Fonts: https://fonts.google.com/specimen/IBM+Plex+Sans.
-sidebar bg: #14152D
- sidebar active row: hsla(238, 38%, 23%, 1)
I also made the font-weight 400 to address the readability issue.
I think it looks way better 👍
=> update fonts, colors & typography

.circleci/config.yml, content/concepts/circuit-relay.md, content/concepts/content-routing.md, content/concepts/nat.md, content/reference/glossary.md
This gives an overview of NAT and the ways libp2p tries to manage NAT traversal.
@Stebalien I based most of the NAT doc on this comment: https://github.com/libp2p/go-libp2p/issues/375#issuecomment-407122416 - if you could give this a look to see if I got things right that would be sweet.
I started to put the Circuit Relay explanation in the NAT doc, but it seemed to work better on its own, since relays are useful for more than NAT traversal.
This stuff is fairly light on details about how to enable or actually use relays, which is intentional, since that's quite implementation-specific. I'd like to keep the concept docs out of implementation land where possible.  That said, when we do have more usage docs, it would be good to have links back and forth from here to there.
Closes #14 and …
=> Concept docs: nat traversal and relay

.circleci/config.yml
The 1.2 image for ipfs-dns-deploy uses a different version if ipfs-cluster-ctl
I think the cluster may have recently updated, since the 1.1 image just stopped working
=> Use new ipfs-dns-deploy image

content/concepts/peer-id.md
This goes over the basics of PeerIds without getting into the details of public key formats, etc.
For the moment it links to https://github.com/libp2p/specs/pull/100 - we can update once the spec gets merged.
=> Concept doc for peer ids

content/tutorials/getting-started/go.md, static/css/theme-libp2p.css
This adds the Go version of the "Getting Started" tutorial.
It also disables word-wrapping in `pre` tags to make long shell commands easier to read.
Closes #16.
=> Add a "Getting Started" tutorial for go-libp2p

content/tutorials/getting-started/javascript.md
`pingRemotePeer` needs `PeerId` class, we just missed to require it first
=> require PeerId create the peerId in pingRemotePeer

content/tutorials/getting-started/javascript.md
With the latest refactor released with [libp2p/js-libp2p400](https://github.com/libp2p/js-libp2p/pull/400), [libp2p/js-libp2p-ping](https://github.com/libp2p/js-libp2p-ping) module is now deprecated.
=> fix: js ping tutorial

content/tutorials/getting-started/javascript.md
With the new `js-libp2p` version released, the current getting started tutorial is completely outdated now. 
I added a attention notice to this while we work on updating the tutorial
=> chore: add notice for js-libp2p version on getting started tutorial

content/concepts/security-considerations.md
This adds a "Security Considerations" concept article that briefly covers some things you might want to think about if you're building a secure system on top of libp2p, and highlights that the DHT (and to a lesser extent, pubsub) are susceptible to Sybil / Eclipse attacks.
@mgoelzer
=> Add security considerations doc

content/tutorials/getting-started/javascript.md
This PR updates the getting started tutorial to the new async API from `js-libp2p@0.27`.
Some namings were also modified, as `js-libp2p` is moving away from the `bundle` naming since this created some confusion for our users.
=> chore: update js getting started tutorial to async

content/introduction/what-is-libp2p.md
Added live links to two dead /TODO on what-is-libp2p page found at https://docs.libp2p.io/introduction/what-is-libp2p/
Reference Issue #75
=> Fixed 2 TODO links on what-is-libp2p page

content/concepts/peer-id.md
Changes "conecpts" to "concepts".
Docs are looking great btw, thanks for all the hard work.
=> Fix link URL in peer-id.md

content/tutorials/getting-started/go.md
The Getting Started in Go documentation has a code example that imports
`github.com/libp2p/go-libp2p-peerstore` and uses that package's
`InfoFromP2pAddr` and `InfoToP2pAddrs` functions, both of which
are marked as deprecated and document how to update your code. This
PR does so for modern compliance.
=> Remove deprecated code from Getting Started in Go

content/tutorials/getting-started/javascript.md
This PR addresses Issue #80. It seems that the links to the `libp2p-nodejs.js` and `libp2p-browser.js` files constantly change, but hopefully the links that I put will not break in the future. Additionally, there is a broken link in the page that points to the definition of a multiaddress. As a fix, I instead pointed the link to the glossary entry for the multiaddress. Finally the output in the terminal shows the `^C` control character which I am guessing came from copying the terminal output after killing the ping server. This control character was removed from the output.
=> Fixed broken links on js-libp2p getting started tutorial 

content/concepts/protocols.md
Ironically, I think rust-libp2p used to close the stream after responding to a ping, until [they concluded](https://github.com/libp2p/rust-libp2p/issues/1601) that this behaviour didn't conform to [the non-existent specification](https://github.com/libp2p/specs/issues/183).
=> Ping responders don't close the stream

content/tutorials/getting-started/javascript.md
We deprecated secio, but it is still in the docs website
=> chore: update js tutorial switching secio to noise

content/introduction/what-is-libp2p.md
https://noiseproject.org is unrelated with the Noise protocol framework(at https://noiseprotocol.org). This PR corrects that error.
=> Noise website link correction

content/introduction/_index.md, content/tutorials/getting-started/rust.md
This commit links to the main rust-libp2p tutorial in the getting
started section. In addition, given that rust-libp2p is a stable
implementation of the libp2p specification, used in production, mention
rust-libp2p along with go-libp2p and js-libp2p.
---
@momack2 linking the tutorial here as discussed. Could you give this pull request a review?
=> content: Add Rust tutorial and correct rust-libp2p maturity level

content/concepts/addressing.md
In the original version [the Addressing section](https://docs.libp2p.io/concepts/addressing/) contains a broken link to Peer Identity inside the tip.
The link leads to [https://docs.libp2p.io/concepts/addressing/peer-identity/](https://docs.libp2p.io/concepts/addressing/peer-identity/) which returns the error:
`ipfs resolve -r /ipns/docs.libp2p.io/concepts/addressing/peer-identity/: no link named "peer-identity" under bafybeihj4dcfauzvivw5nmukwvccttdl7zocicoa4vqeacz7dur75v7k24`
The fix is simply changing './peer-identity' to './peer-id'.
=> Fixed a broken link to PeerId

content/concepts/addressing.md
The link previously led to https://docs.libp2p.io/concepts/addressing/peer-id/.
Now fixed so it leads to https://docs.libp2p.io/concepts/peer-id/.
See also: #55 
FYI: @momack2
=> Fix broken Peer ID link on Addressing page

content/concepts/circuit-relay.md
This is a first step towards fixing https://github.com/libp2p/docs/issues/110.
Content of this pull request:
- 8e00768488c9658b8b54c5ee5e836476a1814b18: Differentiate v1 and v2
- cde37b5a07d7e714e575f30998d8245af1e6d864: Describe relay process
- cd891e6ebfb81508d3be79f4777d580fe5c54631: Remove AutoRelay description
We have not yet decided how nodes should discover relay nodes via the
AutoRelay service. For now, remove the entire section.
=> content/concepts/circuit-relay: Update docs to v2 changes

content/examples/_index.md
Hej;
I recognized that the current documentation is pointing to an archived repository. This PR redirects the user to the correct location without any hop in between.
Cheers!
=> fix(link): Go example links

content/concepts/circuit-relay.md
The current url uses `github.com` and the site doesn't display the diagram image. I replaced it with `raw.githubusercontent.com` url.
=> content/concepts/circuit: Update diagram url

content/reference/glossary.md
Remove dead link from docs -- the repo it points to has been deprecated.
=> Fix: remove dead link from Glossary

content/tutorials/getting-started/go.md
Previously, this linked to the `go-libp2p-host` pkg, which seems to be deprecated in favor of the `go-libp2p-core/host` pkg.
=> fixed deprecated link to "Host interface" in the "Getting Started" go tutorial

content/tutorials/getting-started/rust.md
This fixes the link for Rust tutorials as the old one was outdated.
=> Fix link for Rust tutorials

content/concepts/transport.md
The Transports concepts page links to the "Protocol Negotiation" page but this hase moved under the "Protocol" page under its own heading.
=> Fix link for Protocol Negotiation

content/concepts/security-considerations.md
Added the missing link for the S/Kademlia paper referenced in the docs on securing routing as linked by one of [the authors' on their Karlsruher Institute of Technology pages.](https://telematics.tm.kit.edu/article.php?publication_id=267&language_id=1)
=> Add missing link to the S/Kademlia paper

content/concepts/peer-id.md
Also "improve this page" section that links to old/closed issue.
=> chore: link to actual peer-id spec

content/reference/dos-mitigation.md
Complete "Update links in dos-mitigation.md" subtask of libp2p/go-libp2p#1556
Note:
Some of the previous links used the `master` branch when linking to code at specific line numbers. The contents of the file were modified and the link no longer pointed to the right line of code
- ex: setting limits on system scope pointed to [limit_defaults.go#L342](https://github.com/libp2p/go-libp2p-resource-manager/blob/master/limit_defaults.go#L342)
Or linked to code not on the master branch but on a specific commit id
- ex: [24b27cc71b7a62340f90d5f057e705cf10d5690f/p2p/protocol/identify/id.go#L150](https://github.com/libp2p/go-libp2p/blob/24b27cc71b7a62340f90d5f057e705cf10d5690f/p2p/protocol/identify/id.go#L150)
To address this, the links now point to the latest tagged version `v0.22.0`
=> docs: update DOS Mitigation links to monorepo

content/concepts/protocols.md
- When writing a section for DHT to provide context for the routing content, noticed that IPFS already has a page for this and we can link to it for now.
- The protocols page will be updated in general in a separate PR - into an index page to refer to various sections, utilize the implementations page, and consider adding a general Protocol IDs table.
- In adding https://github.com/libp2p/docs/pull/186, this offers the opportunity to provide background context for data structures and can add HTs and DHT there as part #183
Please see the latest Fleek preview [here](https://bafybeiai2xswif4g6vdq4srr4ejhc7s7yk2ujeledqk7dwaoqa4yctmrom.on.fleek.co/concepts/protocols/).
=> Link to DHT/Kademlia existing docs

content/introduction/_index.md
Line 77 had duplicated "specifications" with a spelling error in the link. This fork corrects that typo.
=> Corrected typo in Introduction: Data Transmission

content/concepts/addressing.md, content/concepts/circuit-relay.md, content/concepts/nat.md, content/concepts/peers.md, content/concepts/protocols.md, content/concepts/publish-subscribe.md, content/concepts/security-considerations.md, content/concepts/transport.md
- Generalizes the `PeerID` guide to add content for `PeerStore`, but to reconsider structure based on the proposed structure changes. Could also consider creating a section and a dedicated index about peer-specific content
- Part of #33, #35
Please view the latest Fleek preview [here](https://bafybeibizxqqedycmfmmtn4r6o3xtmkr3h6o5hmaajsskxws4eeh4do2xi.on.fleek.co/concepts/peers/).
=> Add PeerStore content & TEMP generalize PeerID guide

content/reference/dos-mitigation.md
Links out to relevant sections of the js-libp2p documentation to enable users to configure the various settings to protect their running nodes.
closes https://github.com/libp2p/js-libp2p/issues/1378
=> docs: add js-libp2p discussion to dos mitigation page

config.toml, content/concepts/transports/_index.md, content/reference/connectivity.md
Adds references to the new connectivity site: connectivity.libp2p.io
- Added a simple reference section doc.
- Added to left nav bar.
- Added ending sentence on the transport index.
- closes #218 
Please view the latest Fleek preview [here](https://bafybeieqpsuyt7tz7un5pyiqsljtevziytx35m7wweuygrjwsojgrezgv4.on.fleek.co/).
=> Add connectivity site references

content/guides/getting-started/javascript.md
This guide is broken for js-libp2p 0.40.0 and has been updated per https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.39-v0.40.md
relates to: https://github.com/libp2p/js-libp2p/issues/1481
=> fix: update js-libp2p guide to comply with 0.40.0

config/_default/config.toml
Noticed that the aliases were't working. Seems like the update to `disableAliases` wasn't captured or accidentally changed back to true.
Example: https://bafybeibnhuacz3x4slidrdjnpmu5ulbvdzoz3z3xoov47mdvq45xgruyny.on.fleek.co/concepts/publish-subscribe/  maps correctly to 
https://bafybeibnhuacz3x4slidrdjnpmu5ulbvdzoz3z3xoov47mdvq45xgruyny.on.fleek.co/concepts/pubsub/overview/
=> update: aliases param to false

content/guides/getting-started/nim.md
Like Rust, our tutorials are kept up to date & ran in our CI, so it's easier to just link them.
=> Add link to Nim tutorials

content/concepts/secure-comm/overview.md
- Adds overview for secure communication 
- Part of https://github.com/libp2p/docs/issues/19
Section this document lives under will become populated with corresponding PRs.
Please view the latest Fleek preview [here](https://bafybeie4vcl5j5hgmg4ejsp5eqkdrzkhw4cdtu7x4w3zbszhylrndabbfm.on.fleek.co/concepts/secure-comm/overview/).
=> add: populate secure comm overview

content/concepts/discovery/overview.md
- Adds content for peer discovery overview
- Part of #250 
- Section this document lives under will become populated with corresponding PRs
- Discovery section initiated in https://github.com/libp2p/docs/pull/259
Please view the latest Fleek preview [here]().
=> add: discovery overview

content/concepts/nat/autonat.md
- Populates the AutoNAT doc
- resolves #171
Please view the latest Fleek preview [here](https://bafybeigs6s3mtdslqqjxbpohizruo6cjmbirqbur2mq6bo2jm4o4emzc2u.on.fleek.co/concepts/nat/autonat/).
=> add: autonat

content/concepts/transports/quic.md
- Adds a section under "QUIC in libp2p" to outline the new codepoint for QUIC v1, `quicv1`.
- resolves #230
Please view the latest Fleek preview [here](https://bafybeienh5ijfzmck6omwrrtincdyk4flhwdsh4xqrdov4v62p642wu3l4.on.fleek.co/concepts/transports/quic/#quic-code-point).
=> add: context for quicv1

content/concepts/multiplex/early-negotiation.md
- Adds content for early muxer negotiation
> Not sure where the best place for this would be with the current structure. It is a new document under the general "multiplexer" section.
- Future diagrams would be key for this document.
- resolves #213, part of #212
Latest preview
Please view the latest Fleek preview [here](https://bafybeid45iq72jql7n2cvlcfz4r4oq3zuar3ier2hj4fsucia2umoyfxl4.on.fleek.co/concepts/multiplex/early-negotiation/).
=> feat: early muxer negotiation

content/concepts/introduction/core-abstractions/connections.md
- replaces https://github.com/libp2p/docs/pull/202; also up-to-date with new theme
- adds content about libp2p connection abstractions
(Outdated preview due to PR not being against master anymore] Please view the latest Fleek preview [here](https://bafybeibqvcs3xgfklk3yxi3b7f3yz33y4okzopldqfka5lpbxsarfirzxi.on.fleek.co/concepts/fundamentals/connections/).
=> feat: connections

content/concepts/appendix/glossary.md, content/concepts/fundamentals/addressing.md, content/concepts/fundamentals/peers.md, content/concepts/nat/circuit-relay.md, content/concepts/security/dos-mitigation.md, content/concepts/transports/listen-and-dial.md, content/concepts/transports/quic.md, content/concepts/transports/webtransport.md, content/guides/getting-started/go.md, content/guides/getting-started/javascript.md
This change aims to update all the addresses across the docs to use the special-purposes addresses specified in [RFC 6890](https://datatracker.ietf.org/doc/rfc6890/).
- 192.0.2.0/24 (TEST-NET-1)
- 198.51.100.0/24 (TEST-NET-2)
- 203.0.113.0/24 (TEST-NET-3)
=> update(docs): non-test-net addresses -> special-purpose addresses for docs

content/concepts/secure-comm/noise.md
- populates the noise document, similar to [TLS](https://docs.libp2p.io/concepts/secure-comm/tls/)
- closes #19
Please view the latest Fleek preview [here](https://bafybeieqnt2njw3m73ttumxuchoo53pwgowf2h5xxghehr3fyqyo2lbruy.on.fleek.co/concepts/secure-comm/noise/).
=> feat: noise

content/concepts/transports/webrtc.md
- Adds content for libp2p webrtc
- resolves #211 
Please view the latest Fleek preview [here](https://bafybeicq2o2nvvbc4ncfpfil2qmfcfg35uh2vsdarqacbsbjbk3zoo7gb4.on.fleek.co/concepts/transports/webrtc/).
=> feat: webrtc

content/concepts/multiplex/yamux.md
- Adds content for yamux
- closes #240
- Section this document lives under will become populated with corresponding PRs
Please view the latest Fleek preview [here](https://bafybeicry2dp6tyy2w4ts2k2hn5dwwkoecikrgiigy4f7qhiq6ir7pxjta.on.fleek.co/).
=> add: yamux

content/concepts/multiplex/mplex.md
- Adds content for mplex
- Closes #241
- Section this document lives under will become populated with corresponding PRs
Please view the latest Fleek preview [here](https://bafybeiff7dd37tqgbc4zdlj6pbkjfoxzunexp6vltiaoxbrjlnw6vayo7e.on.fleek.co/concepts/multiplex/mplex/).
=> add: mplex

content/concepts/introduction/protocols/dht.md
- Adds general document for Kademila DHT, with the intention to use other sections (i.e. routing and discovery) for more focussed material.
Preview unavailable atm as not against master
=> feat: kad-dht

content/concepts/pubsub/overview.md
- Creates a common overview for Pub-Sub similar following a similar approach to the other sections
- Incorporates concepts from the original Pub-Sub doc
- part of #236
Not against master (being worked on)
=> feat: pubsub overview

content/concepts/introduction/protocols/identify.md
Adds identify content to protocols section.
Fleek preview unavailable as PR not against master.
=> feat: identify

content/concepts/introduction/core-abstractions/_index.md, content/concepts/introduction/host.md, content/concepts/introduction/protocols/_index.md
- brief overview of a libp2p host
- resolves #257
(not against master being worked on)
=> feat: host

content/concepts/introduction/protocols/multistream.md
- Adds content for Multistream Select and references new content on connections for further explanations.
- Introduces Protocol Select
- addresses #18 
Not against master (setting this up).
=> feat: multistream-select

content/concepts/nat/dcutr.md
- Adds content for dcutr.
- Part of overall content additions for the NAT section.
Please view the latest Fleek preview [here](https://bafybeidfzde4b4h32j2h3is4p4qgrojkj7pxo6iptx6epjqzfua32ufxyi.on.fleek.co/).
=> feat: dcutr

content/concepts/content-routing/overview.md
- Adds content routing overview to the new content routing section
- part of #253 and incorporates https://github.com/libp2p/docs/pull/192
=> feat: content routing overview

content/concepts/transports/webrtc.md
=> feat: add private-to-private docs

content/concepts/fundamentals/addressing.md
I am not familiar with Hugo so there could be a better way to do this, but the [documentation for addressing](https://docs.libp2p.io/concepts/fundamentals/addressing/) appears to have a syntax error that causes it not to render correctly.
=> fix: syntax error linking to multiaddr spec

content/concepts/introduction/overview.md
Changed the link for "peers" from `/concepts/introduction/fundamentals/peers` to `/concepts/fundamentals/peers` to fix the redirection error.
=> fix(docs): correct broken link for "peers" in the introduction

content/guides/getting-started/javascript.md
- Added a missing comma after the `streamMuxers` property to keep proper object syntax.
- Removed the "libp2p has stopped" output for clearer console feedback during remote peer ping operations.
These changes aim to provide a smoother user experience and enhanced clarity when following the tutorial.
=> fix(tutorial): correct syntax error and refine output in libp2p example

content/concepts/introduction/overview.md
Fixes #327 
Based on #335, this fixes the rest of the dead or broken links on the introduction page.
=> fix(docs): correct broken links in the introduction

content/concepts/contribute/community.md, content/concepts/discovery-routing/overview.md, content/concepts/discovery-routing/rendezvous.md, content/concepts/introduction/overview.md, content/concepts/multiplex/early-negotiation.md, content/concepts/multiplex/mplex.md, content/concepts/nat/dcutr.md, content/concepts/secure-comm/overview.md, content/concepts/secure-comm/tls.md, content/concepts/security/dos-mitigation.md, content/concepts/transports/webrtc.md
Fixes #309 
I used `lychee --verbose --exclude twitter.com ./public/` to check for dead links to fix. `twitter.com` is excluded because [@libp2p](https://twitter.com/libp2p) is not accessible without logging in.
This expands on #337 , which fixed the dead links in the introduction.
=> Repair dead links

content/concepts/transports/webtransport.md
Fix a grammar mistake bringing confusion.
=> fix: grammar mistake in webtransport doc

content/guides/getting-started/go.md
Updates go version requirement on this page: https://docs.libp2p.io/guides/getting-started/go/
Fixes issue #349
=> Go version requirement

content/concepts/appendix/glossary.md, content/concepts/nat/dcutr.md
Addresses https://github.com/libp2p/docs/issues/312
Adds `dcutr` and `signaling server` entries
=> Add dcutr glossary entries

content/concepts/fundamentals/dht.md
Current link (https://curriculum.pl-launchpad.io/curriculum/libp2p/dht/) returns error `500`
=> fix: broken link for launchpad DHT docs

content/concepts/nat/circuit-relay.md
I interpreted the story differently, as in, I thought there were four participants here: me, QmAlice, QmBob, and QmRelay. `I have a peer with the Peer ID QmAlice` meant `I have a friend with Peer ID QmAlice` to me in the first place.
Or the other way around, `I want to give out my address` can be changed to `I want to give out my address of QmAlice`, which may seem verbose.
=> fix: better clarity

content/guides/getting-started/nim.md
- The nim-libp2p documentation URL link is not working
- The updated documentation link is: https://vacp2p.github.io/nim-libp2p/docs/
=> Updated nim-libp2p documentation url

content/guides/getting-started/webrtc.md
as of https://github.com/libp2p/js-libp2p/pull/2606 these are now
preconfigured
=> chore: remove stun servers in webrtc guide

content/guides/getting-started/javascript.md
Mplex is deprecated so replace it with Yamux
=> docs: replace mplex with yamux in js examples

content/guides/getting-started/webrtc.md
Updates the example to include libp2p API changes shipped last year
=> docs: update webrtc example to latest API
